Project_Summa/Home/urls.py
from django.conf.urls import url

from django.conf import settings

from django.conf.urls import include

from django.contrib.auth.views import login
from django.contrib.auth.views import logout

from django.contrib.auth import views as auth_views

from .views import index
from .views import UserLogin
from .views import UserSignupView
from .views import UserLogout

app_name='home'

urlpatterns = [
    # /home/
    url(r'^$', index, name = "index"),
    # default template folder is registration
    url(r'^login/$', UserLogin, name="login"),
    url(r'^signup/$', UserSignupView.as_view(), name="signup"),
    url(r'^logout/$', UserLogout, name='logout'),
    url(r'^analyzer/', include('Analyzer.urls'), name="analyzer"),
    url(r'^projectmanager/', include('ProjectManager.urls'), name="projectmanager"),
    url(r'^contact/', include('Contact.urls'), name="contact"),
    url(r'^testapp/', include('testapp.urls'), name="testapp"),
]

Project_Summa/ProjectManager/urls.py
from django.conf.urls import url

from .views import index
from .views import delete_task
from .views import user_profile
from .views import user_send_message

app_name = "projectmanager"

urlpatterns = [
    # /projectmanager/
    url(r'^$', index , name = "index"),
    url(r'^user-profile', user_profile, name = "profile"),
    url(r'^send-message', user_send_message, name = "sendmessage"),
    url(r'^delete-task', delete_task, name = "deletetask")
]

Project_Summa/Project_Summa/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin

from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

import django.views.defaults

# Do not put $ at the end of url if there's more.
urlpatterns = [
    url(r'^', include('Home.urls'), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^analyzer/', include('Analyzer.urls'), name="analyzer"),
    url(r'^projectmanager/', include('ProjectManager.urls'), name="projectmanager"),
    url(r'^contact/', include('Contact.urls'), name="contact"),
    url(r'^testapp/', include('testapp.urls'), name="testapp")
#    url(r'^404/$', django.views.defaults.page_not_found), not working
]

handler404 = 'Home.views.handler404'
handler403 = 'Home.views.handler403'

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

Project_Summa/ProjectManager/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.db.models.signals import post_init
from django.dispatch import receiver

from decimal import Decimal

# Progress is determined when unitest problem is passed.
# each problem is assigned a value and it is summed up to progress.
class Progress(models.Model):
    progress_name = models.CharField(max_length=100, default="progress_")
    progress_project = models.ForeignKey('Project')
    # progress_task can be assigned to Project itself, or Task under project
    progress_task = models.ForeignKey('Task', null=True, blank=True)
    progress_member = models.ForeignKey('Member', null=True, blank=True)
    # only takes 99.99?
    progress_gauge = models.DecimalField(default=0.00, decimal_places=2, max_digits=3)

    progress_open_date = models.DateTimeField(auto_now=True)
    progress_closed_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return '{}-{}%'.format(self.progress_name, str(self.progress_gauge))

    class Meta:
        pass


class Task(models.Model):
    task_status = models.BooleanField(default=False)
    task_priority = models.IntegerField(default=1)
    # if null=True is added,
    # WARNINGS:
    # ProjectManager.Task.task_related: (fields.W340) null has no effect on ManyToManyField.
    task_related = models.ManyToManyField('self', blank=True)
    task_name = models.CharField(max_length=100, default="task_")
    task_description = models.CharField(max_length=300, null=True, blank=True)
    task_project = models.ForeignKey('Project')
    task_submitter = models.CharField(max_length=100, default="Anonymous", null=True, blank=True)
    # if null=True is added,
    # WARNINGS:
    # ProjectManager.Task.task_members: (fields.W340) null has no effect on ManyToManyField.
    task_members = models.ManyToManyField('Member', blank=True)
    task_initiated_at = models.DateTimeField(auto_now=True)
    task_deadline = models.DateTimeField(null=True, blank=True)
    task_completed_at = models.DateTimeField(null=True, blank=True)

    # cannot put progress_sum function to default with self argument.
    task_progress = models.DecimalField(default=0.00, decimal_places=2, max_digits=3, editable=True)

    def progress_sum(self):
        progresses = self.progress_set.all()
        print(progresses)
        progresses_gauge = 0
        for progress in progresses:
            progresses_gauge += progress.progress_gauge
        print(progresses_gauge)
        return progresses_gauge

    """
    this calls error!
    def save(self, *args, **kwargs):
        if not self.task_progress:
            self.task_progress = self.progress_sum()
            print(self.task_progress)
        super().save(*args, **kwargs)
    """

    def __str__(self):
        return '{}-{} : {}'.format(self.task_name, self.task_project, self.task_members)


import json
def UpdateGraph():
    print("UpdateGraph() Called.")
    dics = {'name': "project_summa", 'children': []}
    fp = open('static/js/ProjectManagerTree.json', 'w', encoding='utf8')
    categories = Category.objects.all()
    for category in categories:
        catdics = {}
        catdics['name'] = category.category_name
        catdics['children'] = []

        projects = category.project_set.all()
        for project in projects:
            prodics = {}
            prodics['name'] = project.project_name
            prodics['children'] = []

            tasks = project.task_set.all()
            for task in tasks:
                tasdics = {}
                tasdics['name'] = task.task_name
                tasdics['children'] = []
                prodics['children'].append(tasdics)
            catdics['children'].append(prodics)
        dics['children'].append(catdics)
    json.dump(dics, fp, indent=4)
    fp.close()


@receiver(post_save, sender=Task)
def post_save_task(sender, instance, created, **kwargs):
    if created:
        #instance = kwargs.pop('instance')
        instance.task_progress = instance.progress_sum()
        instance.save(update_fields=["task_progress"])
        UpdateGraph()





class Member(models.Model):
    """
        TODO: currently this is not instantiated as UserProfile created. untied Member represents T.O.
    """
    member_name = models.CharField(max_length=100, default="member_", help_text="project member nickname")
    member_department = models.CharField(max_length=100 ,
                                         choices=((u'project manager',u'project manager'),
                                                  (u'team manager',u'team manager'),
                                                  (u'freelancer',u'freelancer'),
                                                  (u'backend programmer', u'backend programmer'),
                                                  (u'frontend programmer', u'frontend programmer'),
                                                  (u'undesignated', u'undesignated')),
                                         default="undesignated")

    def __str__(self):
        return '{}-{}'.format(self.member_name, self.member_department)


class Project(models.Model):
    project_status = models.BooleanField(default=False, help_text='True: Done, False: Not Done')
    project_name = models.CharField(max_length=100, default="project_")
    project_members = models.ManyToManyField('Member')
    project_workspaces = models.ManyToManyField('Workspace')
    project_controller = models.ForeignKey('Controller')
    project_category = models.ForeignKey('Category')

    project_start_date = models.DateTimeField(auto_now=True)
    project_end_date = models.DateTimeField(null=True, blank=True)
    project_deadline = models.DateTimeField(null=True, blank=True)

    project_description = models.CharField(max_length=300, null=True,
                                           default="test project_", blank=True)

    def __str__(self):
        return '{} - {} name: {} at {}'.format(
            self.project_controller,
            [workspace.workspace_name for workspace in self.project_workspaces.all()],
            self.project_name,
            self.project_start_date)

    def get_absolute_url(self):
        pass

    def describe(self):
        return '{}'.format(self.workspace_description)

    class Meta:
        pass


class Category(models.Model):
    category_parent = models.ForeignKey('self', null=True, blank=True)
    category_name = models.CharField(max_length=100, default="category_")

    def __str__(self):
        return 'category - {}'.format(self.category_name)


class Workspace(models.Model):
    workspace_name = models.CharField(max_length=100, default="workspace_")
    workspace_controller = models.ForeignKey('Controller')
    workspace_description = models.CharField(max_length=300, default="test workspace_",
                                             null="True", blank=True)
    def __str__(self):
        return 'workspace - {}'.format(self.workspace_name)

    def describe(self):
        return '{}'.format(self.workspace_description)


class Controller(models.Model):
    controller_name = models.CharField(max_length=100, default="controller_")
    controller_description = models.CharField(max_length=300, default="test workspace_")

    def __str__(self):
        return '{}'.format(self.controller_name)

    def describe(self):
        return '{}'.format(self.controller_description)

Project_Summa/UserProfile/models.py
from django.db import models

from django.conf import settings

from django.contrib.auth.models import User

from ProjectManager.models import Project
from ProjectManager.models import Member
from ProjectManager.models import Task

from .views import get_user_profile_folder_filename
from .views import get_user_uploadfile_folder

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    projectinfo = models.OneToOneField(Member, blank=True, null=True)
    profile_location = models.CharField(max_length=50, default="Seoul")
    profile_age = models.IntegerField(blank=True, null=True)
    profile_facebook = models.EmailField(blank=True, null=True) # TODO: social auth
    profile_photo = models.FileField(upload_to=get_user_profile_folder_filename, blank=True, null=True)

    def __str__(self):
        return self.user.username


class UserMessage(models.Model):
    fromuser = models.ForeignKey(UserProfile, related_name='fromuser')
    touser = models.ForeignKey(UserProfile, related_name='touser')

    title = models.CharField(max_length=100, blank=False, default="no title")
    content = models.TextField(null=False, blank=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} : {} to {}'.format(self.title, self.fromuser.user.username, self.touser.user.username)


class UserFile(models.Model):
    '''
    meta data file for user uploaded file
    '''
    file_name = models.CharField(max_length=50)
    file_path = models.FileField(upload_to=get_user_uploadfile_folder, blank=False, null=False)
    file_owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    file_project = models.ForeignKey(Project, blank=True, null=True)
    file_task = models.ForeignKey(Task, blank=True, null=True)

    # class Meta:
    #     abstract = True

Project_Summa/ProjectManager/forms.py
from django import forms

from .models import Category
from .models import Project
from .models import Task


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

Project_Summa/UserProfile/forms.py
from django.forms import ModelForm

from .models import UserProfile
from .models import UserMessage

class UpdateUserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'


class SendUserMessageForm(ModelForm):
    class Meta:
        model = UserMessage
        fields = '__all__'

Project_Summa/UserProfile/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

from ProjectManager.models import Task, Project
#from Analyzer.models import UserImage, UserVideo

# UserProfile doesn't have view.

@login_required
def get_user_profile_folder(instance, filename):
    return "%s/info/%s" % (instance.user.username, filename)


@login_required
def get_user_file_folder(instance, filename):
    return "%s/file/%s" % (instance.user.username, filename)


@login_required
def get_user_imagefile_folder(instance, filename):
    return "%s/imagefile/%s" % (instance.user.username, filename)


@login_required
def get_user_profile_folder_filename(instance, _):
    """
    TODO:
    Currently this path is hardcoded in index, base in ProjectManager and Analyzer Apps.
    Changes should be in accordance with them.
    :param instance:
    :param _:
    :return:
    """
    return "%s/info/profile-photo_%s_%s.jpg" % (instance.user.username, instance.user.username, instance.user.pk)


@login_required
def get_user_upload_profile_photo_callback(instance, filename):
    def get_user_profile_folder_filename(instance, _):
        return "%s/info/profile-photo_%s_%s" % (instance.user.username, instance.user.username, instance.user.pk)
    return get_user_profile_folder_filename


@login_required
def get_user_uploadfile_folder(fileclass, filename):
    '''
    :param upload_apps: classname such as Projects or Task..
    :param filename:
    :return:
    NOTE: FileField has builtin function ._get_path()
    '''
    if isinstance(fileclass, Project):
        return "ProjectManager/%s/%s" % (fileclass.project_name, filename)
    if isinstance(fileclass, Task):
        return "ProjectManager/%s/%s/%s" % (fileclass.task_project.project_name, fileclass.task_name, filename)

    # elif isinstance(fileclass, UserImage): # User file on user folders
    #     return "%s/%s/%s" % (fileclass.image_owner.username, 'image', filename)
    # elif isinstance(fileclass, UserVideo):
    #     return "%s/%s/%s" % (fileclass.image_owner.username, 'video', filename)

Project_Summa/ProjectManager/templates/ProjectManagerDir/calender.html
{% load profile_tag %}

    <script>
    // Workspace panel 에 Calendar 를 표시합니다.
    $(document).ready(function(){

      $(window).load(function() {
        var date = new Date(),
            d = date.getDate(),
            m = date.getMonth(),
            y = date.getFullYear(),
            started,
            categoryClass;

          {% if categories_selected != None %}
  //            alert('yes1');
          {% elif workspaces_selected != None %}
//              alert('yes2');
              {% comment %}

              {% endcomment %}
          {% elif projects_selected != None %}
    //          alert('yes3');
          {% endif %}


          {% for idx in workspaces_selected|length_range %}
        var calendar{{ idx }} = $("#calendar{{ idx }}").fullCalendar({
          header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
          },
          selectable: true,
          selectHelper: true,
          select: function(start, end, allDay) {
            $('#fc_create{{ idx }}').click();

            started = start;
            ended = end;

            $(".antosubmit{{ idx }}").on("click", function() {
              var title = $("#title{{ idx }}").val();
              if (end) {
                ended = end;
              }

              categoryClass = $("#event_type{{ idx }}").val();

              if (title) {
                calendar.fullCalendar('renderEvent', {
                    title: title,
                    start: started,
                    end: end,
                    allDay: allDay
                  },
                  true // make the event "stick"
                );
              }

              $('#title').val('');

              calendar.fullCalendar('unselect');

              $('.antoclose').click();

              return false;
            });
          },
          eventClick: function(calEvent, jsEvent, view) {
            $('#fc_edit').click();
            $('#title2').val(calEvent.title);

            categoryClass = $("#event_type").val();

            $(".antosubmit{{ idx }}").on("click", function() {
              calEvent.title = $("#title{{ idx }}").val();

              calendar.fullCalendar('updateEvent', calEvent);
              $('.antoclose{{ idx }}').click();
            });

            calendar.fullCalendar('unselect');
          },
          editable: true,

          events: [{
            title: 'All Day Event',
            start: new Date(y, m, 1)
          }, {
            title: 'Long Event',
            start: new Date(y, m, d - 5),
            end: new Date(y, m, d - 2)
          }, {
            title: 'Meeting',
            start: new Date(y, m, d, 10, 30),
            allDay: false
          }, {
            title: 'Lunch',
            start: new Date(y, m, d + 14, 12, 0),
            end: new Date(y, m, d, 14, 0),
            allDay: false
          }, {
            title: 'Birthday Party',
            start: new Date(y, m, d + 1, 19, 0),
            end: new Date(y, m, d + 1, 22, 30),
            allDay: false
          }, {
            title: 'Click for Google',
            start: new Date(y, m, 28),
            end: new Date(y, m, 29),
            url: 'http://google.com/'
          }]

        });
          {% endfor %}

        {% for idx in project_selected|length_project_range %}
        var calendar{{ idx }} = $("#calendar{{ idx }}").fullCalendar({
          header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
          },
          selectable: true,
          selectHelper: true,
          select: function(start, end, allDay) {
            $('#fc_create{{ idx }}').click();

            started = start;
            ended = end;

            $(".antosubmit{{ idx }}").on("click", function() {
              var title = $("#title{{ idx }}").val();
              if (end) {
                ended = end;
              }

              categoryClass = $("#event_type{{ idx }}").val();

              if (title) {
                calendar.fullCalendar('renderEvent', {
                    title: title,
                    start: started,
                    end: end,
                    allDay: allDay
                  },
                  true // make the event "stick"
                );
              }

              $('#title').val('');

              calendar.fullCalendar('unselect');

              $('.antoclose').click();

              return false;
            });
          },
          eventClick: function(calEvent, jsEvent, view) {
            $('#fc_edit').click();
            $('#title2').val(calEvent.title);

            categoryClass = $("#event_type").val();

            $(".antosubmit{{ idx }}").on("click", function() {
              calEvent.title = $("#title{{ idx }}").val();

              calendar.fullCalendar('updateEvent', calEvent);
              $('.antoclose{{ idx }}').click();
            });

            calendar.fullCalendar('unselect');
          },
          editable: true,

          events: [{
            title: 'All Day Event',
            start: new Date(y, m, 1)
          }, {
            title: 'Long Event',
            start: new Date(y, m, d - 5),
            end: new Date(y, m, d - 2)
          }, {
            title: 'Meeting',
            start: new Date(y, m, d, 10, 30),
            allDay: false
          }, {
            title: 'Lunch',
            start: new Date(y, m, d + 14, 12, 0),
            end: new Date(y, m, d, 14, 0),
            allDay: false
          }, {
            title: 'Birthday Party',
            start: new Date(y, m, d + 1, 19, 0),
            end: new Date(y, m, d + 1, 22, 30),
            allDay: false
          }, {
            title: 'Click for Google',
            start: new Date(y, m, 28),
            end: new Date(y, m, 29),
            url: 'http://google.com/'
          }]

        });
          {% endfor %}

      });

    });
    </script>

Project_Summa/ProjectManager/templates/ProjectManagerDir/task-form-django-admin.html
<form action="/projectmanager/" method="POST" id="controller-task-post-form">
    {% csrf_token %}
    <div class="modal-body">

        <div>
            <table class="table-striped table-hover controller-form-table">
                <tr>
                    <div class="form-group">
                        <td>
                        <label class="vCheckboxLabel" for="id_task_status">Task status</label>
                        </td>
                        <td>
                        <input id="id_task_status" name="task_status" type="checkbox"/>
                        </td>
                    </div>
                </tr>

                <tr>
                    <div class="form-group">
                        <td><label class="required" for="id_task_priority">Task priority</label></td>
                        <td><input class="form-control" id="id_task_priority" name="task_priority" type="text" value="1" required/>
                        </td>
                    </div>
                </tr>
                <div class="form-group">
                <tr>

                    <td><label for="_controller-task-related">Task related</label></td>
                    <td>
                    <div class="related-widget-wrapper">
                        <select class="selectpicker" data-live-search="true" id="_controller-task-related" form="controller-task-post-form" multiple>
                            {% for task in tasks %}
                                <option value="{{ task.pk }}">{{ task.task_name }}, {{ task.task_project.project_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    </td>
                </tr>
                </div>

                <tr>
                    <td>
                    <label class="required" for="id_task_name">Task name</label>
                    </td>
                    <td>
                    <input class="form-control" id="id_task_name" maxlength="100" name="task_name" type="text"
                           value="task_" required/>
                    </td>
                </tr>

                <tr>
                    <td>
                    <label for="id_task_description">Task description</label>
                    </td>
                    <td>
                    <input class="form-control" id="id_task_description" maxlength="300" name="task_description"
                           type="text"/>
                    </td>
                </tr>

                <tr>
                    <td>
                    <label class="required" for="id_task_project">Task project</label>
                    </td>
                    <td>
                    <div class="related-widget-wrapper">
                        <select class="selectpicker" id="id_task_project" name="task_project" required>
                            {% for project in projects %}
                              <option value="{{project.pk}}">{{ project.project_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    </td>
                </tr>

                <tr>
                    <td>
                    <label for="id_task_submitter">Task submitter</label>
                    </td>
                    <td>
                    <input class="form-control" id="id_task_submitter" maxlength="100" name="task_submitter"
                           type="text" value="Anonymous"/>
                    </td>
                </tr>

                <tr>
                    <td>
                    <label for="_controller-task-members">Task members</label>
                    </td>
                    <td>
                    <div class="related-widget-wrapper">
                        <select class="selectpicker" data-live-search="true" id="_controller-task-members" form="controller-task-post-form" multiple>
                            {% for member in members %}
                            <option value="{{ member.pk }}">{{ member.member_name }}, {{ member.member_department }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    </td>
                </tr>

                <tr>
                    <td>
                    <label for="id_task_deadline_0">Task deadline</label>
                    </td>
                    <td>
                    <p class="datetime">날짜: <input class="form-control" id="id_task_deadline_0"
                                                   name="task_deadline_0" size="10" type="text"/><br/>시각: <input
                            class="form-control" id="id_task_deadline_1" name="task_deadline_1" size="8"
                            type="text"/></p>
                    </td>
                </tr>

            </table>
        </div>

    </div>

    <div class="modal-footer">
        <input type="submit" class="btn btn-primary" data-dismiss="modal"
        data-toggle="modal" value="Post"/>
        <button type="button" class="btn btn-default" data-dismiss="modal"
        data-toggle="modal" data-target="#">Close</button>
    </div>
</form>