Project_Summa/Contact/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import list_post
from .views import view_post
from .views import create_post
from .views import delete_comment

from .views import index

app_name = 'contact'

urlpatterns = [
    # /contact/
    url(r'^$', index, name="index"),
    url(r'^list/$', list_post, name="list"),
    url(r'^list/(?P<pk>[0-9]+)/$', view_post, name="view"),
    url(r'^list/new/$', create_post, name="new"),
    url(r'comments/(?P<pk>[0-9]+)/delete$', delete_comment, name="delete_comment"),
]

Project_Summa/Home/urls.py
from django.conf.urls import url

from django.conf import settings

from django.conf.urls import include

from django.contrib.auth.views import login
from django.contrib.auth.views import logout

from django.contrib.auth import views as auth_views

from .views import index
from .views import UserLogin
from .views import UserSignupView
from .views import UserLogout

app_name='home'

urlpatterns = [
    # /home/
    url(r'^$', index, name = "index"),
    # default template folder is registration
    url(r'^login/$', UserLogin, name="login"),
    url(r'^signup/$', UserSignupView.as_view(), name="signup"),
    url(r'^logout/$', UserLogout, name='logout'),
    url(r'^analyzer/', include('Analyzer.urls'), name="analyzer"),
    url(r'^projectmanager/', include('ProjectManager.urls'), name="projectmanager"),
    url(r'^contact/', include('Contact.urls'), name="contact"),
    url(r'^testapp/', include('testapp.urls'), name="testapp"),
]

Project_Summa/Project_Summa/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin

from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

import django.views.defaults

# Do not put $ at the end of url if there's more.
urlpatterns = [
    url(r'^', include('Home.urls'), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^analyzer/', include('Analyzer.urls'), name="analyzer"),
    url(r'^projectmanager/', include('ProjectManager.urls'), name="projectmanager"),
    url(r'^contact/', include('Contact.urls'), name="contact"),
    url(r'^testapp/', include('testapp.urls'), name="testapp")
#    url(r'^404/$', django.views.defaults.page_not_found), not working
]

handler404 = 'Home.views.handler404'
handler403 = 'Home.views.handler403'

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

Project_Summa/Contact/models.py
from __future__ import unicode_literals

from django.db import models

from django.urls import reverse_lazy

from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=40)
    parent = models.ForeignKey('self', null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.name)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, blank=False, default="no title")
    category = models.ForeignKey(Category)
    image = models.ImageField(upload_to='%Y/%m/%d/', null=True, blank=True)
    content = models.TextField(null=False, blank=False)
    tags = models.ManyToManyField('Tag', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.pk)

    def get_absolute_url(self):
        return reverse_lazy('contact:view', kwargs={'pk': self.pk})


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']


class Tag(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return '{}'.format(self.name)

Project_Summa/Contact/forms.py
from django import forms

from .models import Post
from .models import Comment

from django.forms import ValidationError


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)


class PostForm(forms.ModelForm):
    tagtext = forms.CharField(required=False)

    class Meta:
        model = Post
        fields = ('category', 'title', 'image', 'content', 'tags',)

        widget = {
            'category':forms.TextInput(attrs={'class':'form_control'}),
            'title':forms.TextInput(attrs={'class':'form_control'}),
            # 'image':forms.ClearableFileInput(attrs={'accept':'image/*',
            #                                'onchange':'loadFile(event)'})
        }

    def clean_content(self):
        content = self.cleaned_data['content']
        # banning a word
        if 'fool' in content:
            raise ValidationError('There is an invalid input.')
        return content

Project_Summa/Contact/views.py
import os

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from django.contrib.auth.decorators import login_required

from django.http import HttpResponseBadRequest

from django.core.files.uploadedfile import SimpleUploadedFile


from .forms import PostForm
from .forms import CommentForm

from .models import Post
from .models import Tag
from .models import Comment

import base64


def index(request):
    per_page = 3
    page = request.GET.get('page', 1) ##???
    posts = Post.objects.all().order_by('-created_at', '-pk')
    pg = Paginator(posts, per_page)
    try:
        contents = pg.page(page)
    except PageNotAnInteger:
        contents = pg.page(1)
    except EmptyPage:
        contents=[]
    ctx={
        'posts':contents,
    }
    return render(request, "ContactDir/index.html", ctx)


def create_post(request):
    if request.method == "GET":
        form = PostForm()
    elif request.method == "POST":
        filtered = request.POST.get('filtered_image')
        if filtered:
            filtered_image = get_base64_image(filtered)
            filename = request.FILES['image'].name.split(os.sep)[-1]
            _filedata = {
                'image' : SimpleUploadedFile(
                    filename, filtered_image
                )
            }
        else:
            _filedata = request.FILES

        form = PostForm(request.POST, _filedata)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            tag_text = form.cleaned_data.get('tagtext','') ##???
            tags = tag_text.split(',')
            for _tag in tags:
                _tag = _tag.strip()
                tag,_ = Tag.objects.get_or_create(name=_tag, defaults={'name':_tag})
                post.tags.add(tag)
            return redirect('contact:view', pk=post.pk)
    ctx={
        'form':form,
    }
    return render(request, 'ContactDir/edit_post.html', ctx)


def list_post(request):
    per_page = 3
    page = request.GET.get('page', 1) ##???
    posts = Post.objects.all().order_by('-created_at', '-pk')
    pg = Paginator(posts, per_page)
    try:
        contents = pg.page(page)
    except PageNotAnInteger:
        contents = pg.page(1)
    except EmptyPage:
        contents=[]

    ctx={
        'posts':contents,
    }
    return render(request, 'ContactDir/index.html', ctx)


def view_post(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'GET':
        form = CommentForm(request.GET)
    elif request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect(post) ## get_absolute_url call
    ctx = {
        'post':post,
        'comment_form':form,
    }
    return render(request, 'ContactDir/view_post.html', ctx)


def delete_comment(request, pk):
    if request.method != 'POST':
        raise HttpResponseBadRequest
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect(comment.post)##??


def like_post(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        raise Exception('Bad Request')
    qs = post.like_set.filter(user=request.uesr)


def get_base64_image(data):
    if data is None or ';base64' not in data:
        return None

    _format, _content = data.split(';base64,')
    return base64.b64decode(_content)

Project_Summa/Contact/templates/ContactDir/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Project_Summa/Contact/templates/ContactDir/edit_post.html
{% extends 'ContactDir/filter_post.html' %}
{% load static %}
{% load bootstrap3 %}
{% block body %}
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="hidden" name="filtered_image"/>
	<div id="filter_nav">
		<img src="" id="preview"/>
		<button value="vintage">Vintage</button>
		<button value="sepia">Sepia</button>
	</div>
	{% bootstrap_form form %}
	<p>
		<button type="submit" class="btn btn-primary btn-lg">저장</button>
		<a href="{% url 'contact:list' %}" type="button" class="btn btn-primary btn-lg">
			취소
		</a>
	</p>
</form>
{% endblock %}
{% block jsimport %}
{% endblock %}

Project_Summa/Contact/templates/ContactDir/filter_post.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html>
	<head>

	<title>{% block page_title %}Contact{% endblock %}</title>
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		{% block importcss %}
		{% endblock %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script src="{% static 'vendor/vintageJS-master/dist/jquery.vintage.min.js' %}"></script>
	<script src="{% static 'vendor/vintageJS-master/vintage.presets.js' %}"></script>
	</head>
	<body class="container">
		{% block body %}{% endblock %}
		{% block bodycontent %}{% endblock %}
		{% block jsimport %}{%endblock%}
		<script src="{% static 'MediaFileProcessing/ImageFile/VintageImageFilter.js'%}"></script>
	</body>

</html>

Project_Summa/Contact/templates/ContactDir/view_post.html
{% extends 'ContactDir/filter_post.html' %}
{% load bootstrap3 %}
{% load static %}

{% block importcss %}
	<link href="{% static 'css/bs.callout.css' %}" rel="stylesheet">
	<style>
		.post-font-only{
			font-family : 'Open Sans';
		}
	</style>
{% endblock %}

{% block body %}

<div class="bs-callout bs-callout-warning post-font-only">
	<h4> {{ post.pk }} {{ post.title }} </h4>
	<p align="right"> written by : {{post.user.username}}</p>
	<br/>
	{% if post.image %}
	<div><img src="{{post.image.url}}" style="max-width: 100%;"/></div>
	{% endif %}
	<br/>
	<p>
			{{ post.content }}
	</p>
	<p align="right"> {{ post.created_at }} </p>
</div>


{% for comment in post.comment_set.all %}
	<div class="bs-callout bs-callout-primary post-font-only">
		<p> {{ comment.pk }}</p>
		<p> {{ comment.content }}</p>
		<form method="POST" action="{% url 'contact:delete_comment' pk=comment.pk %}">
			{% csrf_token %}
			<button type="submit">삭제</button>
		</p>
        </form>
	</div>
{% empty %}
	<div class="bs-callout bs-callout-primary post-font-only">
		<p> 댓글이 없습니다. </p>
	</div>

{% endfor %}

<form method="POST" action="">
	{% csrf_token %}
	{% bootstrap_form comment_form %}
	<p>
		<button type="submit" class="btn btn-primary btn-lg">
			{% bootstrap_icon "star" %} 저장 </button>
		<a href="{% url 'contact:list' %}" type="button" class="btn btn-primary btn-lg">
			목록으로
		</a>
	</p>
</form>
{% endblock %}