Project_Summa/Analyzer/urls.py
from django.conf.urls import url

from .views import index
from .views import ml_core
from .views import ksprp # kaggle-santander-product-recommendation-problem
from .views import ktncfmp

#from .views import image_core
from .views import ksfddp # kaggle-state-farm-distracted-driver-detectection-problem
from .views import ktsfmcp

from .views import kocpp # kaggle-outbrain-click-prediction-problem

from .views import nlp_ml_core
from .views import kqqpp # kaggle-quora-question-pairs-problem

from .views import video_analysis
from .views import image_ml_core
from .views import image_preprocess
from .views import FileFieldView

app_name = 'analyzer'

urlpatterns=[
    #/analyzer/
    url(r'^$', index ,name="index"),
    url(r'^image-analysis/$', image_ml_core, name="image-ml-core"),
    url(r'^image-analysis/image-preprocess/$', image_preprocess, name="image-preprocess"),
    url(r'^image-analysis/multiple-image-upload-test/$', FileFieldView.as_view(), name="multiple-image-upload-test"),
    url(r'^ml-core/$', ml_core, name="ml-core"),
    url(r'^nlp-core/$', nlp_ml_core, name="nlp-ml-core"),
    url(r'^kaggle-state-farm-distracted-driver-problem/',
        ksfddp , name="kaggle-state-farm-distracted-driver-problem"),
    url(r'^kaggle-santander-product-recommendation-problem/',
        ksprp , name="kaggle-santander-product-recommendation-problem"),
    url(r'^kaggle-the-nature-conservancy-fisheries-monitoring-problem/',
        ktncfmp, name="kaggle-the-nature-conservancy-fisheries-monitoring-problem"),
    url(r'^kaggle-two-sigma-financial-modeling-challenge-problem/',
        ktsfmcp, name='kaggle-two-sigma-financial-modeling-challenge-problem'),
    url(r'kaggle-quora-question-pairs-problem/',
        kqqpp, name='kaggle-quora-question-pairs-problem'),
    url(r'kaggle-outbrain-click-prediction-problem/',
        kocpp, name='kaggle-outbrain-click-prediction-problem')
]

Project_Summa/Contact/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import list_post
from .views import view_post
from .views import create_post
from .views import delete_comment

from .views import index

app_name = 'contact'

urlpatterns = [
    # /contact/
    url(r'^$', index, name="index"),
    url(r'^list/$', list_post, name="list"),
    url(r'^list/(?P<pk>[0-9]+)/$', view_post, name="view"),
    url(r'^list/new/$', create_post, name="new"),
    url(r'comments/(?P<pk>[0-9]+)/delete$', delete_comment, name="delete_comment"),
]

Project_Summa/Home/urls.py
from django.conf.urls import url

from django.conf import settings

from django.conf.urls import include

from django.contrib.auth.views import login
from django.contrib.auth.views import logout

from django.contrib.auth import views as auth_views

from .views import index
from .views import UserLogin
from .views import UserSignupView
from .views import UserLogout

app_name='home'

urlpatterns = [
    # /home/
    url(r'^$', index, name = "index"),
    # default template folder is registration
    url(r'^login/$', UserLogin, name="login"),
    url(r'^signup/$', UserSignupView.as_view(), name="signup"),
    url(r'^logout/$', UserLogout, name='logout'),
    url(r'^analyzer/', include('Analyzer.urls'), name="analyzer"),
    url(r'^projectmanager/', include('ProjectManager.urls'), name="projectmanager"),
    url(r'^contact/', include('Contact.urls'), name="contact"),
    url(r'^testapp/', include('testapp.urls'), name="testapp"),
]

Project_Summa/ProjectManager/urls.py
from django.conf.urls import url

from .views import index
from .views import delete_task
from .views import user_profile
from .views import user_send_message

app_name = "projectmanager"

urlpatterns = [
    # /projectmanager/
    url(r'^$', index , name = "index"),
    url(r'^user-profile', user_profile, name = "profile"),
    url(r'^send-message', user_send_message, name = "sendmessage"),
    url(r'^delete-task', delete_task, name = "deletetask")
]

Project_Summa/Project_Summa/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin

from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

import django.views.defaults

# Do not put $ at the end of url if there's more.
urlpatterns = [
    url(r'^', include('Home.urls'), name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^analyzer/', include('Analyzer.urls'), name="analyzer"),
    url(r'^projectmanager/', include('ProjectManager.urls'), name="projectmanager"),
    url(r'^contact/', include('Contact.urls'), name="contact"),
    url(r'^testapp/', include('testapp.urls'), name="testapp")
#    url(r'^404/$', django.views.defaults.page_not_found), not working
]

handler404 = 'Home.views.handler404'
handler403 = 'Home.views.handler403'

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

Project_Summa/Home/models.py
from django.db import models

# Create your models here.

Project_Summa/Home/forms.py
from django.contrib.auth import get_user_model

from django.utils.translation import gettext as _

from django import forms


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()

        fields = ['username','password']

        # widgets = {
        #     'username': forms.Textarea(attrs={'cols': 80, 'rows': 20}),
        # }
        labels = {
            'username': _(u'아이디 '),
            'password': _(u'비밀번호 '),
        }
        help_texts = {
            'username': _(''),
        }
        # error_messages = {
        #     'username': {
        #         'max_length': _("아이디 길이는 50자 이하 입니다."),
        #     },
        #}


class SigninForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label=u'비밀번호')
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password']

Project_Summa/Home/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import render_to_response

from django.template import RequestContext

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from UserProfile.models import UserProfile

from django.views.generic import View

from .forms import LoginForm
from .forms import SigninForm


def index(request):
    is_authenticated = request.user.is_authenticated()
    username = request.user.username
    print('index(request) : ',is_authenticated)
    ctx={
       'is_authenticated': is_authenticated,
        'username': username,
    }
    return render(request,'HomeDir/index.html',ctx)


def UserLogin(request):
#TODO: 1.redirect 2.staticfiles
    form = LoginForm()
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        import unicodedata
        # b'TedJeong' (str) -> 'TedJeong' (bytes)
        username = unicodedata.normalize('NFKD',username).encode('ascii','ignore')

        form = LoginForm(request.POST)
        authenticate(username=username, password=password)
        is_authenticated = request.user.is_authenticated()

        print(User.objects.filter(username=username).exists())
        print('form validation :', form.is_valid())
        print(form.errors)
        #if form.is_valid():
            # Form is valid, Auth Fail
        print("Form is valid, Auth Fail")
        if not User.objects.filter(username=username).exists():
            ctx = {
                'form': form,
            }
            return render(request, 'registration/login.html', ctx)
        else:
            user = User.objects.get(username=username)
        print("Form is valid, Auth Success")
        print("UserLogin(request) : ", username, password, user, is_authenticated)
        ctx = {
            'is_authenticated': is_authenticated,
            'username': username,
            'is_login': True,
        }
        # Already Loged in
        if request.user is not None:
            login(request, user)
            return redirect('home:index')
            #return render(request,'HomeDir/index.html',ctx)

    if form.is_valid():
        if is_authenticated == True :
            username = request.user.username
            ctx={
                'is_authenticated': is_authenticated,
                'username': username,
                 }
            return render(request, 'HomeDir/index.html', ctx)

    ctx={
        'form': form,
    }
    return render(request, 'registration/login.html', ctx)


def UserLogout(request):
    logout(request)
    return redirect('home:index')

import os
# Sign in Form
class UserSignupView(View):
    form_class = SigninForm
    template_name = 'registration/signup.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # cleaned_data only counts after .is_valid() is called.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = form.save(commit=False)
            user.set_password(password)
            user.save()
            profile = UserProfile.objects.create(user=user)
            profile.save()
            user = authenticate(username = username, password = password)

            # make media directory
            print(os.getcwd())
            os.makedirs(os.getcwd()+'/media/'+username+'/info')

            if user is not None:
                if user.is_active:
                    login(request, user)
                    print(request.user.username)
                    #'namespace:function'
                    return redirect('home:index')
            else:
                return render(request, self.template_name, {'form':form})
        return render(request, self.template_name, {'form': form})



def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response

def handler403(request):
    response = render_to_response('403.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 403
    return response

Project_Summa/Home/templates/HomeDir/index.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Aerial 1.0 by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Summa</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />

		<noscript>
			<link rel="stylesheet" href="{% static 'home/css/skel.css'%}" />
			<link rel="stylesheet" href="{% static 'home/css/style.css' %}" />
			<link rel="stylesheet" href="{% static 'home/css/style-wide.css' %}" />
			<link rel="stylesheet" href="{% static 'home/css/style-noscript.css' %}" />
		</noscript>
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'home/css/ie/v9.css' %}" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static 'home/css/ie/v8.css' %}" /><![endif]-->

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	</head>
	<body class="loading">
		<div id="wrapper">
			<div id="bg"></div>
			<div id="overlay"></div>
			<div id="main">

				<!-- Header -->
					<header id="header">
						<h1>Project Summa</h1>
                        {% if is_authenticated == False %}
                            <p>Data Analytics &nbsp;&bull;&nbsp; Deep Learning &nbsp;&bull;&nbsp; Django</p>
                        {% elif is_authenticated == True %}
                            <p>Welcome! {{ username }}</p>
                        {% endif %}

						<nav>
							<ul>
                                {% if is_authenticated == False %}
                                <li><a id="login-button" href="{% url 'home:login' %}" type="button" class="fa fa-sign-in"\
                                    value="{{ is_authenticated }}"><span>login</span></a></li>
                                {% elif is_authenticated == True %}
                                <li><a id="logout-button" href="{% url 'home:logout' %}" type="button" class="fa fa-sign-out"\
                                    value="{{ is_authenticated }}"><span>logout</span></a></li>
                                {% endif %}
								<li><a href="{% url 'analyzer:index' %}" class="fa fa-terminal"><span>Analyzer</span></a></li>
								<li><a href="{% url 'projectmanager:index' %}" class="fa fa-group"><span>PM</span></a></li>
								<li><a href="#" class="fa fa-download"><span>Download</span></a></li>
								<li><a href="{% url 'contact:index' %}" class="fa fa-envelope-o"><span>Contact</span></a></li>
							</ul>
						</nav>
					</header>

                    <!-- Modal start -->
                    <div class="modal fade bs-modal-sm" id="myModals" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-sm">
                        <div class="modal-content">
                            <br>
                            <div class="bs-example bs-example-tabs">
                                <ul id="myTab" class="nav nav-tabs">
                                  <li class="active"><a href="#signin" data-toggle="tab">Sign In</a></li>
                                  <li class=""><a href="#signup" data-toggle="tab">Register</a></li>
                                  <li class=""><a href="#why" data-toggle="tab">Why?</a></li>
                                </ul>
                            </div>
                          <div class="modal-body">
                            <div id="myTabContent" class="tab-content">
                            <div class="tab-pane fade in" id="why">
                            <p>We need this information so that you can receive access to the site and its content. Rest assured your information will not be sold, traded, or given to anyone.</p>
                            </div>
                            <div class="tab-pane fade active in" id="signin">
                                <form class="form-horizontal">
                                <fieldset>
                                <!-- Sign In Form -->
                                <!-- Text input-->
                                <div class="control-group">
                                  <label class="control-label" for="userid">Alias:</label>
                                  <div class="controls">
                                    <input required="" id="userid" name="userid" type="text" class="form-control" placeholder="JoeSixpack" class="input-medium" required="">
                                  </div>
                                </div>

                                <!-- Password input-->
                                <div class="control-group">
                                  <label class="control-label" for="passwordinput">Password:</label>
                                  <div class="controls">
                                    <input required="" id="passwordinput" name="passwordinput" class="form-control" type="password" placeholder="********" class="input-medium">
                                  </div>
                                </div>

                                <!-- Multiple Checkboxes (inline) -->
                                <div class="control-group">
                                  <label class="control-label" for="rememberme"></label>
                                  <div class="controls">
                                    <label class="checkbox inline" for="rememberme-0">
                                      <input type="checkbox" name="rememberme" id="rememberme-0" value="Remember me">
                                      Remember me
                                    </label>
                                  </div>
                                </div>

                                <!-- Button -->
                                <div class="control-group">
                                  <label class="control-label" for="signin"></label>
                                  <div class="controls">
                                    <button id="signin" name="signin" class="btn btn-success">Sign In</button>
                                  </div>
                                </div>
                                </fieldset>
                                </form>
                            </div>
                            <div class="tab-pane fade" id="signup">
                                <form class="form-horizontal">
                                <fieldset>
                                <!-- Sign Up Form -->
                                <!-- Text input-->
                                <div class="control-group">
                                  <label class="control-label" for="Email">Email:</label>
                                  <div class="controls">
                                    <input id="Email" name="Email" class="form-control" type="text" placeholder="JoeSixpack@sixpacksrus.com" class="input-large" required="">
                                  </div>
                                </div>

                                <!-- Text input-->
                                <div class="control-group">
                                  <label class="control-label" for="userid">Alias:</label>
                                  <div class="controls">
                                    <input id="userid" name="userid" class="form-control" type="text" placeholder="JoeSixpack" class="input-large" required="">
                                  </div>
                                </div>

                                <!-- Password input-->
                                <div class="control-group">
                                  <label class="control-label" for="password">Password:</label>
                                  <div class="controls">
                                    <input id="password" name="password" class="form-control" type="password" placeholder="********" class="input-large" required="">
                                    <em>1-8 Characters</em>
                                  </div>
                                </div>

                                <!-- Text input-->
                                <div class="control-group">
                                  <label class="control-label" for="reenterpassword">Re-Enter Password:</label>
                                  <div class="controls">
                                    <input id="reenterpassword" class="form-control" name="reenterpassword" type="password" placeholder="********" class="input-large" required="">
                                  </div>
                                </div>

                                <!-- Multiple Radios (inline) -->
                                <br>
                                <div class="control-group">
                                  <label class="control-label" for="humancheck">Humanity Check:</label>
                                  <div class="controls">
                                    <label class="radio inline" for="humancheck-0">
                                      <input type="radio" name="humancheck" id="humancheck-0" value="robot" checked="checked">I'm a Robot</label>
                                    <label class="radio inline" for="humancheck-1">
                                      <input type="radio" name="humancheck" id="humancheck-1" value="human">I'm Human</label>
                                  </div>
                                </div>

                                <!-- Button -->
                                <div class="control-group">
                                  <label class="control-label" for="confirmsignup"></label>
                                  <div class="controls">
                                    <button id="confirmsignup" name="confirmsignup" class="btn btn-success">Sign Up</button>
                                  </div>
                                </div>
                                </fieldset>
                                </form>
                          </div>
                        </div>
                          </div>
                          <div class="modal-footer">
                          <center>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </center>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- Modal end-->


				<!-- Footer -->
					<footer id="footer">
						<span class="copyright">&copy; TedJeong <a href="https://github.com/TedJeong" class="fa fa-github"></a></span>
					</footer>

			</div>
		</div>

        <!-- init.js folder contains css file path -->
        <script type="text/javascript" charset="utf-8">
            var init_style_css = "{% static 'home/css/style.css' %}"
            var init_style_wide_css = "{% static 'home/css/style-wide.css' %}"
            var init_style_normal_css = "{% static 'home/css/style-normal.css' %}"
            var init_style_mobile_css = "{% static 'home/css/style-mobile.css' %}"
            var init_style_mobilep_css = "{% static 'home/css/style-mobilep.css' %}"
        </script>

		<!--[if lte IE 8]><script src="{% static 'home/css/ie/html5shiv.js' %}"></script><![endif]-->

		<script src="{% static 'home/js/skel.min.js'%}"></script>
		<script src="{% static 'home/js/init.js' %}"></script>

        <!-- jQuery -->
        <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        {% block jsimport %}{% endblock %}

	</body>
</html>