django_functionblock_04/django_functionblock/urls.py
from django.conf import settings

from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

from django.contrib import admin
from django.conf.urls import include

from model_block.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^form-block/', include('form_block.urls'), name='form_block'),
    url(r'^model-block/', index, name='model_block'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_functionblock_04/form_block/urls.py
from django.conf.urls import url


from .views import index
from . import views

from .views import modal_form_index
from .views import modal_form_result


app_name = 'form_block'

urlpatterns = [
    #/form_block/
    url(r'^$', index, name='index'),
    url(r'^modal_form_index', modal_form_index, name='modal_form_index'),
    url(r'^basic-upload/$', views.BasicUploadView.as_view(), name='basic_upload'),
    url(r'^modal_form_result', modal_form_result, name='modal_form_result'),
]

django_functionblock_04/form_block/models.py
from django.db import models


# models field type  -  corresponding form field
# Model field	Form field
# AutoField	Not represented in the form
# BigAutoField	Not represented in the form
# BigIntegerField	IntegerField with min_value set to -9223372036854775808 and max_value set to 9223372036854775807.
# BooleanField	BooleanField
# CharField	CharField with max_length set to the model fields max_length
# CommaSeparatedIntegerField	CharField
# DateField	DateField
# DateTimeField	DateTimeField
# DecimalField	DecimalField
# EmailField	EmailField
# FileField	FileField
# FilePathField	FilePathField
# FloatField	FloatField
# ForeignKey	ModelChoiceField (see below)
# ImageField	ImageField
# IntegerField	IntegerField
# IPAddressField	IPAddressField
# GenericIPAddressField	GenericIPAddressField
# ManyToManyField	ModelMultipleChoiceField (see below)
# NullBooleanField	NullBooleanField
# PositiveIntegerField	IntegerField
# PositiveSmallIntegerField	IntegerField
# SlugField	SlugField
# SmallIntegerField	IntegerField
# TextField	CharField with widget=forms.Textarea
# TimeField	TimeField
# URLField	URLField

class SampleModel(models.Model):
    modelfield_1 = models.CharField(max_length=100)
    modelfield_2 = models.IntegerField(null=True, blank=True)
    modelfield_3 = models.BooleanField(default=False)
    modelfield_4_1 = models.DateField(auto_now_add=True)
    modelfield_4_2 = models.DateField(null=True, blank=True)
    modelfield_5 = models.DecimalField(decimal_places=5,max_digits=5,null=True, blank=True)
    modelfield_6 = models.FileField(null=True, blank=True)
    modelfield_7 = models.EmailField(null=True, blank=True)

class ImageModel(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='photos/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

django_functionblock_04/form_block/forms.py
from django import forms

from .models import SampleModel
from .models import ImageModel
from django.utils.translation import ugettext_lazy as _
#
# django form attributes append
# 0. models.py 1. forms.py 2. views
# In Html code
# Q. how to access for formfield
# Q. How to access attribute and value for formfield

# decorator
from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class SampleForm(forms.Form):
    #  formField gets arguments as default widget takes arguments
    formfield_1 = forms.BooleanField(required=False, initial=True, label='firstly')
    formfield_2_1 = forms.CharField(widget=forms.TextInput(attrs={'class':'classattr_css'}))
    formfield_2_2 = forms.CharField(initial='name')#, attrs={'class':'classattr_css'}
    formfield_2_3 = forms.CharField(widget=forms.Textarea, max_length=100, help_text='same with initial')
    formfield_2_4 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'trial'})) # initial not working, passwordIput extends TextInput
    formfield_2_5 = forms.CharField(widget=forms.HiddenInput)
    formfield_2_6 = forms.CharField(widget=forms.CheckboxInput)
    formfield_2_7 = forms.CharField(widget=forms.Select(choices=((1,'one'),(2,'two'))))
    formfield_2_8 = forms.CharField(widget=forms.RadioSelect(attrs={'class': 'hello'}, choices=((1,'first'),(2,'second'),(3,'third')))) # default Select()
    formfield_2_2_1 = forms.CharField(error_messages={'required':'your name! please!'}) # when required is failed
    formfield_2_2_2 = forms.TextInput(attrs={'title':'txtinput'})
    formfield_2_2_2.render('nametest','valuetest') # name and value

    formfield_3 = forms.ChoiceField(choices=((1,'one'),(2,'two')))

    formfield_4_1 = forms.DateField(input_formats=['%Y-%m-%d',],initial='2016-12-1', widget=forms.TextInput(attrs={"onfocus":"return this.value=''"}))
    formfield_4_2 = forms.DateField(widget=DateInput())
    formfield_5 = forms.BooleanField(required=False, initial=True)
    formfield_6 = forms.EmailField(widget=forms.TextInput(attrs={'class':'classattr_css'}))
    formfield_7 = forms.FileField(widget=forms.FileInput(attrs={'class':'btn btn-primary bn-file'}))
    formfield_7_2 = forms.FileField()
    formfield_7_3 = forms.ImageField(widget=forms.TextInput(attrs={'class':'btn btn-primary'}))
    #formfield_8 = forms.FilePathField(choices=((1,'a'),(2,'b')))
    # SampleForm(auto_id=False,initial={'formfield_1':'1'},prefix='tsmp')



class SampleModelForm(forms.ModelForm):
    class Meta:
        model = SampleModel
        #fields = ('firstfield',)
        fields = '__all__'
        error_messages = {}
        widgets = {
            'modelfield_1': forms.Textarea(attrs={'cols': 80, 'rows': 20}),
        }
        labels = {
            'modelfield_1': _('Writer'),
        }
        help_texts = {
            'modelfield_1': _('Some useful help text.'),
        }
        error_messages = {
            'modelfield_1': {
                'max_length': _("This writer's name is too long."),
            },
        }

class ImageModelForm(forms.ModelForm):
    class Meta:
        model = ImageModel
        fields = ('file', )

django_functionblock_04/form_block/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from django.http import JsonResponse

from django.views import View

from .models import SampleModel
from .models import ImageModel

from .forms import SampleForm
from .forms import SampleModelForm
from .forms import ImageModelForm

def index(request):
    # auto_id : generate name and id field automatically as id_%s
    # initial :
    # prefix :
    # SampleForm(auto_id=False,initial={'formfield_1':'1'},prefix='tsmp')
    form = SampleForm(auto_id=False)
    modelform = SampleModelForm()

    ctx={
        'form':form,
        'modelform':modelform,
    }
    return render(request, 'form_block/index.html', ctx)

def modal_form_index(request):
    modelform = SampleModelForm()
    print(request.method)
    if request.method == 'POST':
        model = SampleModel
        modelform = SampleModelForm(request.POST, request.FILES)
        print('request get post!')
        print(modelform.is_valid())
        if modelform.is_valid():
            model = modelform.save(commit=False)
            print('model is loaded!')
            ctx = {
                'model': model,
            }
            return redirect('form_block:modal_form_result',ctx)

    ctx = {
        'form': modelform,
    }

    return render(request, 'form_block/modal_form_index.html', ctx)

# redirect, render, HttpResponse, JsonResponse
# redirect(modelinstance) get_absolute_url
# hardcode html
# url resolver {% url 'appname:viewname' %}
# reverse, reverse_lazy
#

def modal_form_result(request):
    return render(request,'modal_form_result.html')


class BasicUploadView(View):
    def get(self, request):
        image_list = ImageModel.objects.all()
        return render(self.request, 'form_block/index.html',
                      {'images': image_list})

    def post(self, request):
        image_form = ImageModelForm(self.request.POST, self.request.FILES)
        if image_form.is_valid():
            image = image_form.save()
            data = {'is_valid': True, 'name': image.file.name, 'url': image.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)

django_functionblock_04/form_block/templates/form_block/index.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load static %}
{% load staticfiles %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <style>
        .classattr_css{
            background-color:black;
        }
        .btn-file {
            position: relative;
            overflow: hidden;
        }
        .btn-file input[type=file] {
            position: absolute;
            top: 0;
            right: 0;
            min-width: 100%;
            min-height: 100%;
            font-size: 100px;
            text-align: right;
            filter: alpha(opacity=0);
            opacity: 0;
            outline: none;
            background: white;
            cursor: inherit;
            display: block;
        }
    </style>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </head>
    <body>
==================================================================================<br/>
            form.as_p<br/>
==================================================================================<br/>
            {{ form.as_p }}
        <br/><br/>
==================================================================================<br/>
            form.as_ul<br/>
==================================================================================<br/>
        <ul>
            {{ form.as_ul }}
        </ul>
        <br/><br/>
==================================================================================<br/>
            form.as_table<br/>
==================================================================================<br/>
        <table>
            {{ form.as_table }}
        </table>
        <br/><br/>
==================================================================================<br/>
            form.is_multipart<br/>
==================================================================================<br/>
        {{ form.is_multipart }}
        <br/><br/>
==================================================================================<br/>
            form.formfield_4.value<br/>
==================================================================================<br/>
        {{ form.formfield_4.value }}

        <br/><br/>
==================================================================================<br/>
            form.formfield_4<br/>
==================================================================================<br/>
        form.formfield_4 : {{ form.formfield_4 }}
        <br/>
        form.isinstance.formfield_4 : {{ form.isinstance.formfield_4 }}
        <br/>
        form.data.formfield_4 : {{ form.data.formfield_4 }}
        <br/>


==================================================================================<br/>
            modelform.as_p<br/>
==================================================================================<br/>
        {{ modelform.as_p}}



==================================================================================<br/>
        {# 1. BUTTON TO TRIGGER THE ACTION #}
        <button type="button" class="btn btn-primary js-upload-photos">
          <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
        </button>

        {# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
        <input id="fileupload" type="file" name="file" multiple
               style="display: none;"
               data-url="{% url 'form_block:basic_upload' %}"
               data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

        {# 3. TABLE TO DISPLAY THE UPLOADED PHOTOS #}
        <table id="gallery" class="table table-bordered">
          <thead>
            <tr>
              <th>Image</th>
            </tr>
          </thead>
          <tbody>
            {% for image in images %}
              <tr>
                <td><a href="{{ image.file.url }}">{{ image.file.name }}</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>


         <!-- jQuery -->
        <script src="{% static 'jquery/jquery.js' %}"></script>
        <script src="{% static 'jquery/jquery.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'jquery_file_upload/vendor/jquery.ui.widget.js' %}"></script>
      <script src="{% static 'jquery_file_upload/jquery.iframe-transport.js' %}"></script>
      <script src="{% static 'jquery_file_upload/jquery.fileupload.js' %}"></script>



        <script>
            $(function () {
              /* 1. OPEN THE FILE EXPLORER WINDOW */
              $(".js-upload-photos").click(function () {
                $("#fileupload").click();
              });

              /* 2. INITIALIZE THE FILE UPLOAD COMPONENT */
              $("#fileupload").fileupload({
                dataType: 'json',
                done: function (e, data) {  /* 3. PROCESS THE RESPONSE FROM THE SERVER */
                  if (data.result.is_valid) {
                    $("#gallery tbody").prepend(
                      "<tr><td><a href='" + data.result.url + "'>" + data.result.name + "</a></td></tr>"
                    )
                  }
                }
              });

            });
        </script>


    </body>
</html>

django_functionblock_04/form_block/templates/form_block/modal_form_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load bootstrap3 %}
    {% load static %}

    <!-- Bootstrap Core CSS -->
    <!--<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>


    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>


    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
</head>
<body>

==================================================================================<br/>
            on bootstrap modal modelform.as_p<br/>
==================================================================================<br/>

        <div class="w3-container">
          <h2>W3.CSS Modal</h2>
          <p>Add the w3-card-* class to the w3-modal-content container to display the modal as a card.</p>
          <button onclick="document.getElementById('id01').style.display='block'" class="w3-btn">Open Modal</button>

          <div id="id01" class="w3-modal">
            <div class="w3-modal-content w3-card-8">
              <header class="w3-container w3-teal">
                <span onclick="document.getElementById('id01').style.display='none'"
                class="w3-closebtn">&times;</span>
                <h2>Modal Header</h2>
              </header>
              <div class="w3-container">
                  <form action="{% url 'form_block:modal_form_index' %}" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                    <table>
                      {{ form.as_table }}
                    </table>
                    <p>Some text..</p>
                    <p>Some text..</p>
                  <input type="submit" class="btn btn-primary" value="submit"/>
                  </form>
              </div>
              <footer class="w3-container w3-teal">
                <p>Modal Footer</p>
              </footer>
            </div>
          </div>
        </div>
    {% if model %}
        <p>{{ model.model_field1}}</p>
    {% endif %}



         <!-- jQuery -->
        <script src="{% static 'jquery/jquery.js' %}"></script>
        <script src="{% static 'jquery/jquery.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>




    <script>
    $(function() {
      $( ".datepicker" ).datepicker({
        dateFormat: 'yy/mm/dd'
      });
    });
    </script>
</body>
</html>

django_functionblock_04/form_block/templates/form_block/modal_form_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    this is modal form result <br/>
    {% if model %}
    <p>{{ model.model_field1}}</p>
    {% endif %}

</body>
</html>